[package]
name = "custom_gui_test"
description = "Provides a reusable test plugin for validating custom GUI behaviors in AE."
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = []
catch-panics = []

[dependencies]
after-effects = { workspace = true }
utils = { path = "../../crates/utils" }
ae_ui = { path = "../../crates/ae_ui" }

[dev-dependencies]
pipl = { workspace = true }

[build-dependencies]
chrono.workspace = true
pipl.workspace = true

[lints]
workspace = true
